// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatrolRewardService;

#nullable disable

namespace PatrolRewardService.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20230911113037_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatrolRewardService.Models.PlayerModel", b =>
                {
                    b.Property<string>("AvatarAddress")
                        .HasColumnType("text");

                    b.Property<string>("AgentAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AvatarAddress");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
